[build]
  command = "npm run build"
  publish = "client/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/notes"
  to = "/.netlify/functions/api/notes"
  status = 200

[[redirects]]
  from = "/notes/*"
  to = "/.netlify/functions/api/notes/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

